version: "3.7"
services:
  api:
    build: ./api
    ports: 
      - "8000:8000"
    restart: always
    depends_on:
      - 'sqs'
  converter:
    build: ./converter
    ports: 
      - "3000:3000"
    deploy:
      replicas: 1
      restart_policy:
        max_attempts: 3
        condition: on-failure       
      update_config:
        parallelism: 3
        delay: 10s
    networks: 
      - balance 
    restart: always
    depends_on:
      - 'sqs'
  sqs:
    image: roribio16/alpine-sqs
    ports:
      - "9324:9324"
      - "9325:9325"
    volumes:
      - ./config/elasticmq.conf:/opt/config/elasticmq.conf
  balancer:
    build: ./nginx_balancer
    ports:
      - 80:80
    depends_on:
      - converter
    deploy:
      placement:
        constraints: [node.role == manager]
    networks: 
      - balance

networks:
  balance:
    driver: overlay